//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logica.ServiceTiendaMil {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        private decimal precio_unitarioField;
        
        private byte ivaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((this.idProductoField.Equals(value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal precio_unitario {
            get {
                return this.precio_unitarioField;
            }
            set {
                if ((this.precio_unitarioField.Equals(value) != true)) {
                    this.precio_unitarioField = value;
                    this.RaisePropertyChanged("precio_unitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public byte iva {
            get {
                return this.ivaField;
            }
            set {
                if ((this.ivaField.Equals(value) != true)) {
                    this.ivaField = value;
                    this.RaisePropertyChanged("iva");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTiendaMil.WebServiceVentasSoap")]
    public interface WebServiceVentasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarProductosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProductos", ReplyAction="*")]
        Logica.ServiceTiendaMil.ListarProductosResponse ListarProductos(Logica.ServiceTiendaMil.ListarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<Logica.ServiceTiendaMil.ListarProductosResponse> ListarProductosAsync(Logica.ServiceTiendaMil.ListarProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarXIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarXId", ReplyAction="*")]
        Logica.ServiceTiendaMil.BuscarXIdResponse BuscarXId(Logica.ServiceTiendaMil.BuscarXIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarXId", ReplyAction="*")]
        System.Threading.Tasks.Task<Logica.ServiceTiendaMil.BuscarXIdResponse> BuscarXIdAsync(Logica.ServiceTiendaMil.BuscarXIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarProductos", Namespace="http://tempuri.org/", Order=0)]
        public Logica.ServiceTiendaMil.ListarProductosRequestBody Body;
        
        public ListarProductosRequest() {
        }
        
        public ListarProductosRequest(Logica.ServiceTiendaMil.ListarProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarProductosRequestBody {
        
        public ListarProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logica.ServiceTiendaMil.ListarProductosResponseBody Body;
        
        public ListarProductosResponse() {
        }
        
        public ListarProductosResponse(Logica.ServiceTiendaMil.ListarProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logica.ServiceTiendaMil.Producto[] ListarProductosResult;
        
        public ListarProductosResponseBody() {
        }
        
        public ListarProductosResponseBody(Logica.ServiceTiendaMil.Producto[] ListarProductosResult) {
            this.ListarProductosResult = ListarProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarXIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarXId", Namespace="http://tempuri.org/", Order=0)]
        public Logica.ServiceTiendaMil.BuscarXIdRequestBody Body;
        
        public BuscarXIdRequest() {
        }
        
        public BuscarXIdRequest(Logica.ServiceTiendaMil.BuscarXIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarXIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public BuscarXIdRequestBody() {
        }
        
        public BuscarXIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarXIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarXIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Logica.ServiceTiendaMil.BuscarXIdResponseBody Body;
        
        public BuscarXIdResponse() {
        }
        
        public BuscarXIdResponse(Logica.ServiceTiendaMil.BuscarXIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarXIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Logica.ServiceTiendaMil.Producto BuscarXIdResult;
        
        public BuscarXIdResponseBody() {
        }
        
        public BuscarXIdResponseBody(Logica.ServiceTiendaMil.Producto BuscarXIdResult) {
            this.BuscarXIdResult = BuscarXIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceVentasSoapChannel : Logica.ServiceTiendaMil.WebServiceVentasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceVentasSoapClient : System.ServiceModel.ClientBase<Logica.ServiceTiendaMil.WebServiceVentasSoap>, Logica.ServiceTiendaMil.WebServiceVentasSoap {
        
        public WebServiceVentasSoapClient() {
        }
        
        public WebServiceVentasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceVentasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVentasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVentasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logica.ServiceTiendaMil.ListarProductosResponse Logica.ServiceTiendaMil.WebServiceVentasSoap.ListarProductos(Logica.ServiceTiendaMil.ListarProductosRequest request) {
            return base.Channel.ListarProductos(request);
        }
        
        public Logica.ServiceTiendaMil.Producto[] ListarProductos() {
            Logica.ServiceTiendaMil.ListarProductosRequest inValue = new Logica.ServiceTiendaMil.ListarProductosRequest();
            inValue.Body = new Logica.ServiceTiendaMil.ListarProductosRequestBody();
            Logica.ServiceTiendaMil.ListarProductosResponse retVal = ((Logica.ServiceTiendaMil.WebServiceVentasSoap)(this)).ListarProductos(inValue);
            return retVal.Body.ListarProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Logica.ServiceTiendaMil.ListarProductosResponse> Logica.ServiceTiendaMil.WebServiceVentasSoap.ListarProductosAsync(Logica.ServiceTiendaMil.ListarProductosRequest request) {
            return base.Channel.ListarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Logica.ServiceTiendaMil.ListarProductosResponse> ListarProductosAsync() {
            Logica.ServiceTiendaMil.ListarProductosRequest inValue = new Logica.ServiceTiendaMil.ListarProductosRequest();
            inValue.Body = new Logica.ServiceTiendaMil.ListarProductosRequestBody();
            return ((Logica.ServiceTiendaMil.WebServiceVentasSoap)(this)).ListarProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logica.ServiceTiendaMil.BuscarXIdResponse Logica.ServiceTiendaMil.WebServiceVentasSoap.BuscarXId(Logica.ServiceTiendaMil.BuscarXIdRequest request) {
            return base.Channel.BuscarXId(request);
        }
        
        public Logica.ServiceTiendaMil.Producto BuscarXId(int id) {
            Logica.ServiceTiendaMil.BuscarXIdRequest inValue = new Logica.ServiceTiendaMil.BuscarXIdRequest();
            inValue.Body = new Logica.ServiceTiendaMil.BuscarXIdRequestBody();
            inValue.Body.id = id;
            Logica.ServiceTiendaMil.BuscarXIdResponse retVal = ((Logica.ServiceTiendaMil.WebServiceVentasSoap)(this)).BuscarXId(inValue);
            return retVal.Body.BuscarXIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Logica.ServiceTiendaMil.BuscarXIdResponse> Logica.ServiceTiendaMil.WebServiceVentasSoap.BuscarXIdAsync(Logica.ServiceTiendaMil.BuscarXIdRequest request) {
            return base.Channel.BuscarXIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Logica.ServiceTiendaMil.BuscarXIdResponse> BuscarXIdAsync(int id) {
            Logica.ServiceTiendaMil.BuscarXIdRequest inValue = new Logica.ServiceTiendaMil.BuscarXIdRequest();
            inValue.Body = new Logica.ServiceTiendaMil.BuscarXIdRequestBody();
            inValue.Body.id = id;
            return ((Logica.ServiceTiendaMil.WebServiceVentasSoap)(this)).BuscarXIdAsync(inValue);
        }
    }
}
